package Utilities.constans;

public enum Design_Status {
	ALL_PATIENT_CASES,
	VERIFY_STL_FILES,
	SUBMIT_DESIGN,
	REVISION_REQUESTED,
	AWAITING_DESIGN_APPROVAL,
	SUBMIT_STL_FILES,
	COMPLETED,
	EXPIRED,
	ARCHIVED
}
